### ISSUE TITLE
Core Game Engine Development

### ISSUE THREAD

**Issue by nicktagliamonte** [nicktagliamonte/In-the-City#1]
- [x] #1 Set Up Basic Project Structure
- [x] #2 Implement Core Game Loop and logic
- [x] #3 Develop Input Handling System
- [ ] #4 Create the save/load system framework (simple file based)
- [x] #5 Define classes and stats for the pc

**Comment by nicktagliamonte** [comment]
removed modularly implement and test levels, because that is 90% of the work of the whole game and does not belong as a sub-task under game engine development.
